### ISSUE TITLE
Markers fail to render for albersUSA

### ISSUE THREAD

**Issue by itsjoekent** [zcreativelabs/react-simple-maps#79]
The following throws an error on my map when using AlbersUSA projection,

```
              {events.map(event => {
                const marker = {
                  coordinates: event.geoLocation,
                  name: event.title,
                };

                return (
                  <Marker marker={marker} key={event.id}>
                    <circle cx={0} cy={0} r={10} />
                  </Marker>
                );
              })}
```

The error happens because it's calling `clipAngle` on the projection but clipAngle doesn't exist,
https://github.com/zcreativelabs/react-simple-maps/blob/423a5aea814e1be7626801fbafb04aa717f180a4/src/Marker.js#L117

I was able to change the compiled src,
```
var isGlobe = projection.clipAngle() === degrees;
```

to

```
var isGlobe = false;
```

and the markers successfully rendered.

**Comment by itsjoekent** [comment]
👍 no problem - I would offer to make a PR but I am not very knowledgeable in mapping, or math haha

**Comment by andy14312** [comment]
Hello, When will the repo be updated with this bug fix? I'm planning to use this in my project

**Comment by zimrick** [comment]
Should be fixed now [v0.12.1](https://github.com/zcreativelabs/react-simple-maps/releases/tag/0.12.1).

**Comment by samuel-belcastro** [comment]
@zimrick this still happens but now with error: TypeError: Invalid attempt to destructure non-iterable instance

Passing array coordinates with albersUSA projection fails. I switched projections and it worked fine

**Comment by Maintrain97** [comment]
@zimrick I am experiencing the same issues reported above by @samuel-belcastro

**Comment by rekoke** [comment]
@zimrick I am experiencing the same issues, using geoPolyhedralWaterman projection and panning the map.
Any update?
